# Autogenerated wrapper script for easi_jll for aarch64-apple-darwin-mpi+openmpi
export libeasi

using ASAGI_jll
using HDF5_jll
using LLVMOpenMP_jll
using Lua_jll
using NetCDF_jll
using yaml_cpp_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("easi")
JLLWrappers.@declare_library_product(libeasi, "@rpath/libeasi.dylib")
function __init__()
    JLLWrappers.@generate_init_header(ASAGI_jll, HDF5_jll, LLVMOpenMP_jll, Lua_jll, NetCDF_jll, yaml_cpp_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libeasi,
        "lib/libeasi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
