# Autogenerated wrapper script for easi_jll for aarch64-unknown-freebsd-mpi+mpitrampoline
export libeasi

using ASAGI_jll
using CompilerSupportLibraries_jll
using HDF5_jll
using Lua_jll
using NetCDF_jll
using yaml_cpp_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("easi")
JLLWrappers.@declare_library_product(libeasi, "libeasi.so")
function __init__()
    JLLWrappers.@generate_init_header(ASAGI_jll, CompilerSupportLibraries_jll, HDF5_jll, Lua_jll, NetCDF_jll, yaml_cpp_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libeasi,
        "lib/libeasi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
