# Autogenerated wrapper script for easi_jll for x86_64-apple-darwin-cxx11
export libeasi

using CompilerSupportLibraries_jll
using Lua_jll
using yaml_cpp_jll
JLLWrappers.@generate_wrapper_header("easi")
JLLWrappers.@declare_library_product(libeasi, "@rpath/libeasi.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Lua_jll, yaml_cpp_jll)
    JLLWrappers.@init_library_product(
        libeasi,
        "lib/libeasi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
